### ISSUE TITLE
File endings in templates/, should they be .template instead?

### ISSUE THREAD

**Issue by dbeecham** [aperezdc/vim-template#100]
My vim do not like to edit some files in templates/, because some addons thinks the file name determine file type. Eclim are by far the worst offender for this in my setup, making editing =template=.java very tedious. Can the files be named "c.template", instead of "template.c"?

**Comment by dbeecham** [comment]
I would like to add that tab-completion in the templates/ directory can feel slightly wierd in my opinion. My brain would like to go "htm<tab>", but right now the best way is "<tab>.ht<tab>".

**Comment by muff1nman** [comment]
#91 is kinda related to this. Can you try an empty prefix as suggested there?

**Comment by aperezdc** [comment]
@dbeecham Hi there! Did the suggestion from @muff1nman help? Can we close this issue or is there still something that needs fixing?

**Comment by dbeecham** [comment]
We can close this issue. :) Thanks for reminding me.
