### ISSUE TITLE
Plugin not working on SunOS 5

### ISSUE THREAD

**Issue by dagoss** [aperezdc/vim-template#102]
This plugin is not working on our system (SunOS 5.10)

This is the output I get when I try to apply a template (with `templates_debug=1`)

    :Template *.c
    Executing `find -L '' -maxdepth 1 -type f -name '.vim-template:*'`
    No template found
    Executing `find -L '/hdrs/goss/.vim/bundle/vim-template/templates/' -maxdepth 1 -type f -name '=template=*'`
    No template found

The cause seems to be the find command. Apparently the version of `find` on this system doesn't support the `-maxdepth` option. If I manually run that command without the `-maxdepth` option, the templates are found.

Not sure if this is a common scenario. I've been using this plugin on other systems (Windows and Linux) without this issue.

**Comment by muff1nman** [comment]
dc100647129843a8b37c21824cf9e3c333086fac brought in the find command to allow searching for hidden files.

I'm thinking we have a couple options:
1. Catch any errors in the find command and fallback to the builtin glob
2. Find a better way to glob for hidden files
3. Allow the user to disable use of the find command (maybe a max_portability flag?)

2 is obviously the best option, but iirc I couldn't find a way in vimscript to glob on hidden files. 1 might be a good intermediate solution, while 3 is probably the least ideal in my mind as it adds a confusing option for the user.

**Comment by aperezdc** [comment]
Another idea would be trying to use `find <plugindir> -maxdepth 1 -name README.rst` when the plugin is loaded, and detect whether invoking `find` worked successfully. If that command failed, we can assume that the version of `find` available in the system does not support `-maxdepth` and use the builtin `glob()` function as fallback. WDYT?

**Comment by dagoss** [comment]
#104 appears to have fixed this issue on SunOS. I use this plugin on a couple of OS. I'll open another issue if I find something else.
