### ISSUE TITLE
 Unknown function: pathogen#infect

### ISSUE THREAD

**Issue by dgodfrey95** [aperezdc/vim-template#110]
I followed the instructions as was written in the README. In the README for pathogen.vim it said if you are new to vim and lacking a vimrc create one and copy-paste this into it:

```
execute pathogen#infect()
syntax on
filetype plugin indent on
```

But now when I open vim I get

Error detected while processing /c/Users/dgodfrey/.vimrc:
line    1:
E117: Unknown function: pathogen#infect
E15: Invalid expression: pathogen#infect()

**Comment by dgodfrey95** [comment]
I was able to solve the problem by going into the .vimrc file and insert "set nocp" (without the quotes) at the top of the file.

**Comment by dgodfrey95** [comment]
I thought I was able to fix it. I couldn't. The error comes up in the git bash tool whenever I want to open a file with vim.

**Comment by aperezdc** [comment]
The error message means that Pathogen is not loaded. Which means that probably you have the `pathogen.vim` in the wrong directory. Can you double check that you have the file at `c:\Users\dgodfrey\vimfiles\autoload\pathogen.vim`? Note that in the Pathogen READMEit says about replacing `~/.vim` with `~/vimfiles` when using it in Windows, and `~` means your user directory.

**Comment by dgodfrey95** [comment]
Yes, when I do "ls ~/.vimfiles/autoload" it gives pathogen.vim.

**Comment by dgodfrey95** [comment]
It turned out I didn't do the `~/vimfiles` translation correctly. I fixed it but I still get the same error.

`mkdir -p ~\vimfiles/autoload ~\vimfiles/bundle && curl -LSso ~\vimfiles/autoload/pathogen.vim https://tpo.pe/pathogen.vim`

**Comment by aperezdc** [comment]
@dgodfrey95 Which version of Vim for are you using? Is it the prebuilt Vim for Windows available at http://www.vim.org/download.php#pc?

**Comment by dgodfrey95** [comment]
Maybe I chose the wrong one. At the top of the page I chose the "self-installing executable" for MS-WINDOWS.

**Comment by aperezdc** [comment]
@dgodfrey95: Yes, that is the prebuilt version from `vim.org` I mentioned. As per your comment it looks like Pathogen is placed in the correct location. If you still have this issue, could you provide a log file of the Vim startup? You can get it with:

```sh
vim -V9logfile.txt -c :q
```

and then atatching `logfile.txt` log here.

**Comment by aperezdc** [comment]
@dgodfrey95 Have you managed to get things working? Or if not, could you provide a log file?

**Comment by dgodfrey95** [comment]
Sorry for the long time to reply. Yes I did get it working. Thank you.

**Comment by aperezdc** [comment]
@dgodfrey95 No problem, thanks for letting us know! This way we can close this issue.

**Comment by garretzou** [comment]
@dgodfrey95 Man, same problem for me, please tell me how you figure out it, Thanks

**Comment by raffihsieh** [comment]
I figured out my problem.
in Windows 10, I moved my files from ~/vimfiles to ~/.vim and it started working
