### ISSUE TITLE
Error on creating file

### ISSUE THREAD

**Issue by PieerotGG** [aperezdc/vim-template#111]
Hello all,
I started to use vim yesterday but I've got an error, i enabled vim debug with:
`let g:templates_debug = 1`

And the output is:

```Messages maintainer: Bram Moolenaar <Bram@vim.org>
Executing `find -L '/home/pierre/' -maxdepth 1 -type f -name '.vim-template:*'`
No template found
Executing `find -L '/home/' -maxdepth 1 -type f -name '.vim-template:*'`
No template found
Executing `find -L '/' -maxdepth 1 -type f -name '.vim-template:*'`
No template found
Executing `find -L '/home/pierre/.vim/bundle/vim-template/templates/' -maxdepth
1 -type f -name '=template=*'`
No template found
```

Pathogen is working because NERDTree is working, if I list the files in .vim/bundled/vim-templates/templates I have this output:

[OUTPUT](https://gyazo.com/4afc11ad5318635e06dc07d3ca473dbc)

Thank you !

**Comment by PieerotGG** [comment]
This is my .vimrc:
```
" Enable debug mode
let g:templates_debug = 1

" Executing patogen execute mode
execute pathogen#infect()

" Enabling the syntax
syntax on

" File type plugin
filetype plugin indent on

" Show line number
:set number
```

**Comment by FliiFe** [comment]
Fixed with `set shell=/bin/bash` for me.
See #107

**Comment by aperezdc** [comment]
I have added a note to the `README` file, and also started with a Troubleshooting/FAQ section in the documentation (see #108). That will hopefully be helpful to the people who may stumble upon this again :wink:
