### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [aperezdc/vim-template#112]
Can you add a how to use section in the readme or wiki?

I don't see anything telling me how to add templates and associate them with a language of choice. It only says it can do that.

**Comment by aperezdc** [comment]
@ZelphirKaltstahl: The included documentation has an `USAGE` section already.You can browse it from within Vim using the following command:

```vim
:help template.txt
```

Alternatively, you can [browse it directly from the Git repository](https://github.com/aperezdc/vim-template/blob/master/doc/template.txt#L26).

**Comment by aperezdc** [comment]
@ZelphirKaltstahl: I have added a note in the `README` file pointing to the actual documentation. That should help :wink:
