### ISSUE TITLE
Is it possible to match against a path?

### ISSUE THREAD

**Issue by tterranigma** [aperezdc/vim-template#130]
I would like files created in a specific folder to use a specific template. The issue that those files are bash scripts without a suffix, ie `custom/scripts/script1`. 

How should I name the template that I want to have?

**Comment by aperezdc** [comment]
Unfortunately it's not currently possible to match paths. I suppose you could use a Vim autocommand like the following (untested):

```vim
autocmd BufNewFile custom/scripts/* Template .sh
```

**Comment by tterranigma** [comment]
To also make it work with NERDTree, this is what I ended up with:

```vim
  function! s:load_template()
    " if file empty
    if line('$') == 1 && getline(1) == ''
     Template .sh
    endif
  endfunction

  augroup MyTemplate
    autocmd!
    autocmd BufNewFile,BufReadPost scripts/custom/* :call <SID>load_template()
  augroup END
```
