### ISSUE TITLE
can it search recursively?

### ISSUE THREAD

**Issue by Freed-Wu** [aperezdc/vim-template#138]
such as`let g:templates_directory = ['~/mytemplates']`, and it can search recusively all the directories of `~/mytemplates`? such as `~/mytemplates/latex`, `~/mytemplates/context`, and if i `:Template latex/mylatex.tex` it will use template of `~/mytemplates/latex/mylatex.tex`? (`let g:templates_global_name_prefix = ''`)

**Comment by aperezdc** [comment]
@Freed-Wu Sorry, currently passing template names with slashes to `:Template` is not supposed to work, and the `g:templates_directory` is not searched recursively.

**Comment by Freed-Wu** [comment]
I create [a plugin](https://github.com/Freed-Wu/template.vim) for myself to replace this plugin, so I must close all my issues of this repo because I cannot reproduce any of them.
