### ISSUE TITLE
Are multiple occurrences of the same variable on the same line supposed to work?

### ISSUE THREAD

**Issue by danielfalbo** [aperezdc/vim-template#147]
In my `=template=.tex` I have the following line:
```
\author{\Large %AUTHOR% --- \texttt{\href{mailto:%MAIL%}{%MAIL%}}}
```
.

When I open a new `.tex` file, the first `%MAIL%` turns into the actual value of my `g:mail` variable, while the second one doesn't (i.e.:
```
\author{\Large Daniel Falbo --- \texttt{\href{mailto:danielfalbo@engineer.com}{%MAIL%}}}
```
). I can also replace `%MAIL%` with any other variable (for example, `%USER%`) and the same thing happens.

Is this a bug or is it a choice not to use the same variable twice in the same line?

**Comment by danielfalbo** [comment]
There was probably something bad in my `init.vim` because I don't have this issue anymore 👍

**Comment by danielfalbo** [comment]
For people here because they have the same issue, I just discovered that the problem was `set gdefaults`, removing it from my `init.vim` solves this issue.

**Comment by aperezdc** [comment]
@danielfalbo Sorry for the late reply. I'm glad that you got things working :pray: 

This is a known issue, and it is [mentioned in the FAQ section](https://github.com/aperezdc/vim-template/blob/618d3f2713ab300b9d8e755fd9fbc43d4f394d7e/doc/template.txt#L320) of the documentation.
