### ISSUE TITLE
About search path

### ISSUE THREAD

**Issue by guotsuan** [aperezdc/vim-template#26]
I'm wondering about in the current order of searching the template, if possible, one can have a more option:

old:
1) current directory or top directory ---> 2) default temples directory in the plugin 

new: 
1) current directory or top directory --->

 1.5 ) one directory specify by the user, e.g. ~/.vim/mytemplates.

 2) default temples directory in the plugin 

So people can change the default templates and put there and have higher rank than the default one. The way users can leave the official templates unchanged, which is easy for updating later by version control system.

Thanks,

Quan

**Comment by aperezdc** [comment]
This is now implemented. Additional global templates will be searched from the directory set in the  `g:templates_directory` variable.
