### ISSUE TITLE
Not work in Win7 64bit

### ISSUE THREAD

**Issue by hellojujian** [aperezdc/vim-template#38]
Hi, bro, I use this plugin in Win7 64bit with Gvim7.4, a few month ago, it works very well, and then i update plugins using command :BundleUpdate, now it not work.
In dir vim-template/templates there was no files, i tried to create a new file named "=template=*.c", but Win7 tells that "*" was not legal in file name, so is this the reason? if so, how can i make it work?

**Comment by aperezdc** [comment]
Maybe we shold rename the built-in templates to have file names which work both for Unix and Windows, and provide a default sensible setting for `g:templates_tr_in` and `g:templates_tr_out`. People are still hitting file system naming issues (see issue #54). IMHO cloning the repo should “just work” also in Windows.
