### ISSUE TITLE
Separate the base templates from the plugin itself

### ISSUE THREAD

**Issue by japboy** [aperezdc/vim-template#40]
I like this plugin. Thanks for the great effort.

It would be nice if I can separate the base templates from the plugin itself so that I can change them without git conflicts when updating the plugin.

How about `~/.vim-template` for the base template directory?

**Comment by aperezdc** [comment]
With the latest changes it is possible to define a list of directories where to search for templates, for example:

```
let g:templates_directory = ['/path/to/directory1', '/path/to/directory2']
```

and it is also possible to disable using the built-in templates, using:

```
let g:templates_no_builtin_templates = 1
```

So both of the behaviours we discussed in this issue are now implemented and I consider this issue closed. If there is something else to be done or any missing bits, please comment and re-open it.

Happy new 2015!

**Comment by japboy** [comment]
Happy new year :+1:
