### ISSUE TITLE
Missing last line in an old file

### ISSUE THREAD

**Issue by zhaoxuan** [aperezdc/vim-template#41]
When I use  ':Template *.sh' in a file, I missing last line of it.

vim a.sh

    echo 'first line'
    #something
    echo 'last line'

Input :Template *.sh, the file will chang to this:

    #! /bin/sh
    #
    # a.sh
    # Copyright (C) 2014 john <john@apple.local>
    #
    # Distributed under terms of the MIT license.
    #
    
     echo 'first line'
     #something
    
Where is my last line?

**Comment by muff1nman** [comment]
#34 closed.
