### ISSUE TITLE
How to add my c's template and not affect update?

### ISSUE THREAD

**Issue by arcticlion** [aperezdc/vim-template#52]

**Comment by aperezdc** [comment]
@arcticlion: If I understand correctly, you want to know how to have your own templates without modifying the ones included with `vim-template`, isn't it? If that's the question, it is the same as in issue #26 which I have just resolved: you can put `let g:templates_directory = '...'` in your `.vimrc` to specify an additional directory where to search for global templates, and that way you won't need to change the built-in ones included with the plug-in.

Does that work for you, or is your question related to a different thing?

**Comment by arcticlion** [comment]
Yes, it is. But I meet some trouble. I create a file named \=template=\*.c in ~/dotfile and put let g:templates directory = '../dotfile' in .vimrc.

Regret not to work.



-- 
Finch
Sent with Airmail

在 2015年1月2日 下午9:55:56, Adrian Perez (notifications@github.com) 写到:

@arcticlion: If I understand correctly, you want to know how to have your own templates without modifying the ones included with vim-template, isn't it? If that's the question, it is the same as in issue #26 which I have just resolved: you can put let g:templates_directory = '...' in your .vimrc to specify an additional directory where to search for global templates, and that way you won't need to change the built-in ones included with the plug-in.

Does that work for you, or is your question related to a different thing?

**Comment by aperezdc** [comment]
@arcticlion: Please use the full path for `g:templates_directory` (using `~` should work, too). Could you please try with `let g:templates_directory = '~/dotfile'`? That should work.

**Comment by arcticlion** [comment]
Sorry, I try let g:templates_directory = '~/dotfle' and let g:templates_directory = '/Users/MasterMac/dotfile'.

But it don’t work.


-- 
Finch
Sent with Airmail

在 2015年1月2日 下午9:55:56, Adrian Perez (notifications@github.com) 写到:

@arcticlion: If I understand correctly, you want to know how to have your own templates without modifying the ones included with vim-template, isn't it? If that's the question, it is the same as in issue #26 which I have just resolved: you can put let g:templates_directory = '...' in your .vimrc to specify an additional directory where to search for global templates, and that way you won't need to change the built-in ones included with the plug-in.

Does that work for you, or is your question related to a different thing?

**Comment by muff1nman** [comment]
You have a typo. 

`g:templates_directory = '~/dotfle'` should instead be `g:templates_directory = '~/dotfile'`
