### ISSUE TITLE
Defining a New Template Directory Raises 'Illegal Variable Name' Error

### ISSUE THREAD

**Issue by churay** [aperezdc/vim-template#53]
When I attempt to define a new template directory using the newest version of the plugin (e.g. `let g:templates_directory='~/.vim/templates'` in `.vimrc`), I get the following error message:

```
Error detected while processing ~/.vim/bundle/vim-template/plugin/templates.vim:
line  455:
E461: Illegal variable name: l:directory
Press ENTER or type command to continue
```

I believe that this error is being caused because the variable `l:directory` is scoped as a local function variable when it doesn't exist in the scope of a function.  Changing the scoping of this variable to be local to the script (i.e. to `s:directory`) fixes this error and properly sets the template directory.

Is this actually an error or am I just setting the templates directory incorrectly?  If it is an error, would you like me to submit a pull request or would you rather make the correction?  If not, what is the proper way to set a new templates directory?

Thanks in advance for your help.

**Comment by aperezdc** [comment]
A fix has just been pushed that should have solved this issue (it certainly does for me!)

@churay, @arcticlion: Could you please pull the changes from the Git repo and confirm that this issue is solved for you as well?

**Comment by churay** [comment]
The fix solved the issue for me as well!  Thank you!

**Comment by aperezdc** [comment]
@churay: Great, thanks for confirming!
