### ISSUE TITLE
Different Template for same extension

### ISSUE THREAD

**Issue by sagarrakshe** [aperezdc/vim-template#59]
Is there any configuration, to choose between different templates for same extension?
For example, when I am writing office code (say *.js), the template header should contain my office mail-id, but when I am working on my side-project it should display my personal mail-id.
This is just the case with the mail-id, I want to change many other fields.

**Comment by muff1nman** [comment]
There is not any configuration within vim-template to do this. Variables such as email are driven using global variables. However, you may be able to achieve what you want using directory specific vimrc files and a plugin/autoload. See https://github.com/embear/vim-localvimrc and http://stackoverflow.com/questions/1889602/multiple-vim-configurations. In the former, you would probably have `g:email` set to be someone@work.com in your global vimrc but in your ~/awesome/side/project/directory you could set `g:email` to be someone.else@sideproject.org in the hope that it would override `g:email`. 

If you get one of these to work, please let us know so other users can benefit as well :smile:

**Comment by sagarrakshe** [comment]
Problem solved. I kept a project specific vim file (**.vim.custom**) in the project directory.
Added the following code to vimrc and set the g:email to my personal mail id.
`if filereadable(".vim.custom")`
    `so .vim.custom`
`endif`

The only disadvantage or rather pain is that vim must be started in the right directory, where the **.vim.custom** file lies.
