### ISSUE TITLE
expand %$ENV_VAR%

### ISSUE THREAD

**Issue by linuxcaffe** [aperezdc/vim-template#62]
Here's an idea: why not make all available environment variables available for expansion, with a magic "$"?

**Comment by aperezdc** [comment]
I agree that this would be interesting, but maybe it would be even better to have the existing syntax, and use the environment variable if defined, and if it is not defined then the usual value would be used. Or maybe the other way around, dunno. The idea that comes to mind is that, for example, `%USER%` could be taken from the environment when `g:user` is not defined... Or maybe it would even make sense that there is a general environment-overrides-values rule in general, and that some particular variables are treated the other way around. Mmh, probably it is best to give this some thought before implementing.

**Comment by linuxcaffe** [comment]
I guess it should be a simple as possible, but no simpler ;-)
To my (simple) mind, it makes sense to use ENV_VAR first, and then override with g:user config, but it does deserve some Deep Thought.

**Comment by muff1nman** [comment]
Perhaps this could be done using the user defined variables?  In your vimrc you could test if an environment variable is present and if so add it to `g:templates_user_variables`?

**Comment by aperezdc** [comment]
I agree with @muff1nman that this can already be done with user-defined variables in a more controller fashion.
