### ISSUE TITLE
configuration confusion

### ISSUE THREAD

**Issue by linuxcaffe** [aperezdc/vim-template#63]
Hi! I'm trying to setup vim-template for use with vimwiki files, but I'm somewhat confused about the configuration, it's not working yet..

I would like to create
<pre>
vim ~/.task/project/foo.project.wiki
</pre>
with template file 
<pre>
~/.vim/template/project.template
</pre>
and so far .vimrc config
<pre>
let g:templates_directory = '~/.vim/template'
let g:templates_name_prefix = '.template.'
let g:templates_global_name_prefix = 'template:'
let g:templates_fuzzy_start = 1
</pre>
with no success.. what am I doing wrong?

**Comment by muff1nman** [comment]
The documenation seems to be a bit misleading here and perhaps a new ticket is needed to address it.

With that aside, the couple immediate issues I see are as follows:

* `g:templates_name_prefix` and g:templates_global_name_prefix` are strings that need to be at the begining of a template name. Or in otherwords, `project.template` should really be something like `template:project.wiki`
* Note that `g:templates_name_prefix` will be used only when searching up the directory tree while `g:templates_global_name_prefix` will only be used when searching for templates in the global templates directory.
* `g:templates_directory` is not valid. It is actually called `g:template_dir`. Again, this is a documentation issue as I see you pulled that straight from the readme. 

Hope that helps

**Comment by linuxcaffe** [comment]
Helps a lot! Works!
thanks sooo much!!
