### ISSUE TITLE
integrate vim :r[ead] command with %R_file|exe%

### ISSUE THREAD

**Issue by linuxcaffe** [aperezdc/vim-template#65]
I'm no vim expert, but it seems to me that the function of the vim :r[ead] command is similar to expanding a template variable. It would open up a whole world of "expandables", and considering vim-templete uses.. well.. vim, it only seems natural.

replace ":r\<space\>" with "%R_"
<pre>
The Foo File
%R_~/files/foo.txt%
</pre>
is the tip of the iceberg!

**Comment by muff1nman** [comment]
Since there hasn't been much activity and I am not completely clear on what you are after, I am going to close this. Feel free to submit a PR if you would like to see this implemented.

**Comment by linuxcaffe** [comment]
Closed yes, but I think this is such an awesome idea, that it could replace/ obviate all of the other existing features, and so, I'm gonna try to describe it, k?

The idea here is to add 2 new variables that behave as though the vim :read command were used at the variable location. For example;

%R_~/foo/example.txt% would insert the contents of ~/foo/example.txt

and 

%R!_date% would insert the output of the date command

with these two variations of the vim-read-command-as-variable, anything would be possible, without defining user-variables, and even potentially even replacing the existing default variables, which you probably wouldn't want to do ;-)

there, I splained it! Thanks!

**Comment by aperezdc** [comment]
@linuxcaffe: Thanks for the explanation, the proposed feature is much clearer now. Plainly reading a file an inserting it in the place of expansion could be something interesting for people maintaining complex sets of templates where some common parts are picked from separate files (e.g. the license snippet for multiple templates could be read from a single place). While that would be useful, it opens a can of worms... consider the following questions:

- Are template variables expanded in included files too?
- If so, what would happen if a template includes itself recursively?
- Let's say we allow recursive inclusions: is there a maximum number of inclusion levels? How many exactly?
- How about template A including template B, and template B including template A (or, in general: any series of inclusions which ends up in a loop)?

And that's questions just from the top of my head. To me it looks like this feature can potentially add a lot of complexity. And for `%R!_command%` there are even more things to take into account.

Personally, I would prefer to keep the plugin simple, but if there are compelling reasons to implement this kind of functionality, please tell about them, and give some use-case examples where this feature would make a difference. For now it just seems like a “this sounds like it would be cool” feature request.
