### ISSUE TITLE
trouble with too many, or too few, name elements

### ISSUE THREAD

**Issue by linuxcaffe** [aperezdc/vim-template#71]
I'm having great success with vim-template for my primary purpose; templated [taskwiki](https://github.com/tbabej/taskwiki) files named "foo.project.wiki", works great applying "~/.vim/templates/template.project.wiki".

what's _not_ working, and I can't figure out why, is in making index files for that wiki, named "index.wiki". The template "template.index.wiki" isn't generating for the new file "index.wiki", I guess because the name is all suffix.. 

on the other side of the coin, taskwarrior sub-projects are "." delimited, like "project:foo.bar"
and so I'd like to create sub-project files 
named "foo.bar.project.wiki" 
and have %FILE% = 'foo.bar'
but that isn't working, generates %FILE% = 'foo', which isn't surprising, just not what I'm after..

any suggestions appreciated, thanks

**Comment by muff1nman** [comment]
> what's not working, and I can't figure out why, is in making index files for that wiki, named "index.wiki". The template "template.index.wiki" isn't generating for the new file "index.wiki", I guess because the name is all suffix.. 

Can you post your vimrc / vim-template configs and the `ls` of any custom template directories?

> on the other side of the coin, taskwarrior sub-projects are "." delimited, like "project:foo.bar"
and so I'd like to create sub-project files
named "foo.bar.project.wiki"
and have %FILE% = 'foo.bar'
but that isn't working, generates %FILE% = 'foo', which isn't surprising, just not what I'm after..

Not sure I understand, but perhaps you could try a user defined function to get the correct name?

vimrc:
```
function GetWikiName()
        return substitute(expand("%:t"), ".project.wiki$", "", "")
endfunction

let g:templates_user_variables = [["WIKI_NAME", "GetWikiName"]]
```

=template=.project.wiki
```
WIKI_NAME: %WIKI_NAME%
```

Then `vim a.test.project.wiki` should result in:

```
WIKI_NAME: a.test
```
