### ISSUE TITLE
Windows 8.1 X64, "Not yet implemented"

### ISSUE THREAD

**Issue by blueyi** [aperezdc/vim-template#76]
Windows 8.1 X64,GVIM, when I test it ,I got a prompt "Not yet implemented".

How can i fix the Error,thank you!

![Uploading 2015-07-19_160045.png…]()

**Comment by muff1nman** [comment]
Closing this as the code path causing this error has been removed. Feel free to open a new issue if you run into more troubles.

**Comment by blueyi** [comment]
Thank you fixed the issue,I have updated vim-template by git pull,but I got another error like the picture,how could i revise it ,thanks!
![2015-10-14_090105](https://cloud.githubusercontent.com/assets/6254020/10472422/d9842cba-7252-11e5-8f20-f300c8f1a064.jpg)

**Comment by muff1nman** [comment]
Silly, I closed #87, without actually merging it. Pull and try again

**Comment by blueyi** [comment]
Thank you, it work very well, but maybe some where I haven't configured well, when I creat a new .cpp file use gvim, I only got this
![2015-10-14_111746](https://cloud.githubusercontent.com/assets/6254020/10474139/9de05f5e-7265-11e5-861e-997c078e3c5e.jpg)
![2015-10-14_111759](https://cloud.githubusercontent.com/assets/6254020/10474140/9de26ac4-7265-11e5-8167-3f4ca8fa0320.jpg)

Is I need to  config a cpp template for the .cpp file? Or use some else configure for vim-template in .vimrc
Thanks. 
Best regards.

**Comment by muff1nman** [comment]
The issue here is how git on windows is handling linux symlinks. The content of `testvim.cpp` is exactly what git uses to denote a symlink. If you don't mind, can you open a new bug for this?

**Comment by blueyi** [comment]
Thank you,I have create a new issue in here https://github.com/aperezdc/vim-template/issues/88
Please forgive my terrible English
