### ISSUE TITLE
cpp templates are not working

### ISSUE THREAD

**Issue by intelaravind** [aperezdc/vim-template#83]
Hi,

The cpp templates are not loaded automatically. The c works fine. 

I installed the plugin using vundle and I verified that the link from "c template " to "cpp template" is not broken. If I replace the link with a copy of the file, it works perfectly. 

I also tried (for checking) the command ":Template *.c" , which is working. But ":Template *.cpp" is not working.

**Comment by muff1nman** [comment]
Hmm. Fascinating. I have a hunch that this may have been broken by #77. Thanks for the heads up!

**Comment by muff1nman** [comment]
Fixed in #86
