### ISSUE TITLE
Make the plugin search ONLY in provided custom template directory

### ISSUE THREAD

**Issue by shikhanshu** [aperezdc/vim-template#85]
How can I avoid the searching in current directory and parents? I only want the plug-in to search in the path I provide for custom templates. Can a switch be added?

**Comment by muff1nman** [comment]
Currently the only way to control the pwd and parent search is with `g:template_max_depth`. However the way it is currently implemented, it is only possible to limit the search to pwd by setting `g:template_max_depth = -1`. 

So rather than adding a switch, it might be best to change how `g:template_max_depth` works. Perhaps the following:

0 - Do not search PWD or parents
1 - Search PWD but not parents
2 - Search PWD and one parent
...

**Comment by shikhanshu** [comment]
Good idea.

**Comment by aperezdc** [comment]
@muff1nman: I like your idea of changing the meaning of `g:template_max_depth`. I am not sure if the name of the `g:template_max_depth` is very descriptive... maybe it could be better, but I cannot thing of a much better name...

**Comment by shikhanshu** [comment]
With the new meaning, template_search_depth may be a good name. It will be
used to control the depth of search for templates.

Whatever value it is set to, the provided custom template path will be
searched first, and then current path etc as per the depth variable.

**Comment by aperezdc** [comment]
Using `g:template_search_depth` could be a reasonably good name, yes. So, I think this should go this way:

1. Rename the variable to `g:template_search_depth` with the semantics indicated above.
2. If `g:template_search_depth` is not defined, fall-back and check for `g:template_max_depth`. If the latter is defined, convert its value to the corresponding `g:template_search_depth` setting _and_ warn the user about using a deprecated setting.

Does this sound okay?

**Comment by shikhanshu** [comment]
Sounds good to me. Thanks!

**Comment by muff1nman** [comment]
Small tweak.. How about `g:template_search_height` since it searches up, not down?

**Comment by muff1nman** [comment]
And actually to keep it similar to the other variables it probably should be `g:templates_search_height`

**Comment by shikhanshu** [comment]
Makes sense.


Thanks,
Shikhanshu

**Comment by muff1nman** [comment]
Small addition:

**-1 - Search PWD and all parents**
0 - Do not search PWD or parents
1 - Search PWD but not parents
2 - Search PWD and one parent
