### ISSUE TITLE
"Set default templates"

### ISSUE THREAD

**Issue by manelgarcia** [aperezdc/vim-template#90]
Is there a way to use only certain templates, ie: only php/html/js, on new files without deleting the other template files?

Thanks and congratulations, great plugin!

**Comment by muff1nman** [comment]
Easiest way I can think of is to copy the desired builtin templates to a user defined local directory and set the flag to ignore the builtin templates. Let us know if you need more guidance.

**Comment by manelapartum** [comment]
I'll try that, thanks a lot!

**Comment by manelgarcia** [comment]
I'll try that, thanks a lot!
