### ISSUE TITLE
Combining vim-template and nautilus document templates naming conventions

### ISSUE THREAD

**Issue by iagomosqueira** [aperezdc/vim-template#91]
I am trying to unify the template files used by vim-template and those available with Nautilus "New document" context menu. I have pointed both vim-template and Nautilus to the same folder when looking for template files, but I haven't found a way of merging both naming conventions.

Nautilus wants filed to be named R\ file.R to show as "R file" in the context menu, but vim-template expects a common filename and only different extensions, say file.R.

Is there any way of specifying g:templates_global_name_prefix to achieve this? Would I need to modify every time this variable is used to create the right string by pasting the extension and a space before g:templates_global_name_prefix?

**Comment by muff1nman** [comment]
Interesting. Do you have a reference that describes the nautilus document templates in greater detail?

**Comment by iagomosqueira** [comment]
Not a full Nautilus reference, found out through these links



http://gnome-look.org/content/show.php?content=39317



http://askubuntu.com/questions/208291/how-to-create-a-new-blank-file-in-nautilus-3-6-and-above



and testing it myself. Could not find anything about changing Nautilus naming convention.





 ---- On Thu, 05 Nov 2015 03:05:21 +0100 muff1nman &lt;notifications@github.com&gt; wrote ----




Interesting. Do you have a reference that describes the nautilus document templates in greater detail?

**Comment by muff1nman** [comment]
The one thing I can think of that may work for you is specifying an empty prefix: `let g:templates_global_name_prefix = ""`. Then you would have templates named like `txt` without any prefix.

**Comment by iagomosqueira** [comment]
I am not sure that will work with Nautilus. But if no easy solution is 
available I do not think it is worth too much effort.

**Comment by muff1nman** [comment]
I thought I tested it and had it working, but other than that I cannot think of an easy solution.

**Comment by iagomosqueira** [comment]
Thanks. Not such an essential feature.
