### ISSUE TITLE
vim crashes when creating new files

### ISSUE THREAD

**Issue by m-wells** [aperezdc/vim-template#94]
I'm having a strange issue where anytime I try to create a new file vim crashes.  For instance, when I type `vim foobarnew.sh` I get:
```
"foobarnew.sh" [New File]
[11]+  Stopped                 vim foobarnew.sh
```
and then if I follow it up with `exit` I get `There are stopped jobs.`
When I move vim-template out of the `.vim/bundle` directory everything works (except of course vim-template).  I haven't added any new packages and haven't modified my vimrc for a while so I have no idea what is going on.

Just to clarify, this doesn't just happen with `*.sh` files, this happens with any filename, even when I don't provide an extension.

**Comment by muff1nman** [comment]
Can you please add let g:templates_debug=1 to your .vimrc and then post the results of editing a file with logging enabled? e.g. vim -V9vim-template.log test.txt

**Comment by muff1nman** [comment]
Okay so you mentioned that vim-template works when you disable all other plugins? Have you tried reenabling plugins one by one to figure out which one is actually giving you troubles?

**Comment by m-wells** [comment]
I added `let g:templates_debug=1` to my `~/.vimrc` and ran `vim -V9vim-template.log test.txt`

    Executing `find -L '/home/mark/testdir/' -maxdepth 1 -type f -name '.vim-template:*'`
    
    [1]+  Stopped                 vim -V9vim-template.log test.txt


I've attached the `vim-template.log` file (I had to rename it to `vim-template.log.txt` because github doesn't support `*.log` files.
[vim-template.log.txt](https://github.com/aperezdc/vim-template/files/63517/vim-template.log.txt)

**Comment by m-wells** [comment]
Let me try to clarify my issue.  Anytime I try to create a new file of any sort vim will crash if I have vim-template enabled.  If I move it out of the way then I can create new files just fine.

**Comment by muff1nman** [comment]
Can you try removing julia-vim?

**Comment by muff1nman** [comment]
Also have you tried resuming the process? It hasn't really crashed, but just sent to the background for some odd reason. If there is only one background process it can be resumed using `fg`.
