### ISSUE TITLE
Plugin doesn't seem to be loaded

### ISSUE THREAD

**Issue by bbrcan** [aperezdc/vim-template#99]
Hi there!

I'm getting the same issue as in https://github.com/aperezdc/vim-template/issues/49, however the suggested fix does not seem to work for me.

When I open a new file - say, `blah.c` - no template is created. When I try to manually invoke the command `:Template *.c`, I get the following error:

```
E492: Not an editor command: Template *.c
```

The output of `:echo exists(":Template")` is `0`.

I've also tried with other file-types, such as `*.py` and `*.sh`, but with no luck.

I've installed the plugin via Vundle, and `~/.vim/bundle/vim-template` most certainly exists.

As per the above thread, I also ran `vim +BundleInstall +qall`.

Any suggestions on why the plugin might not be loading?

I've attached my `~/.vimrc` file, as well as the output of `vim --version`. 

Thanks in advance :)

Ben

[vim_version.txt](https://github.com/aperezdc/vim-template/files/150268/vim_version.txt)
[vimrc.txt](https://github.com/aperezdc/vim-template/files/150269/vimrc.txt)

**Comment by bbrcan** [comment]
Hi all,

This is embarrassing! It was a Vundle configuration issue. My fault! 

I was missing the following:

```
call vundle#end()  
```

Which means none of my plugins were working via Vundle! The only reason any of them worked was because I had installed them manually before moving to Vundle.

Apologies! Hopefully this helps someone .. ?

**Comment by aperezdc** [comment]
@bbrcan: No need to apologize. An issue with the configuration could have happened to anyone. Glad that you find the issue yourself :wink:
